/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#C13B2D",
        "primary-hover": "#A8311E",
        "primary-soft": "#F5DDD8",
        "on-primary": "#FFFFFF",
        secondary: "#E5A532",
        "secondary-soft": "#FFF4DD",
        neutral: "#F7F4ED",
        ink: "#1A1A1F",
        "ink-soft": "#2D2D34",
        slate: "#5C5C66",
        "slate-soft": "#8F8F99",
        cream: "#F7F4ED",
        parchment: "#FAF7F0",
        "surface-white": "#FFFFFF",
        divider: "#E8E2D5",
        "divider-strong": "#D4CCBA",
        success: "#2D8A4F",
        "success-deep": "#1F6638",
        "success-soft": "#DCEFE2",
        warning: "#C97A1F",
        "warning-deep": "#8C5612",
        "warning-soft": "#FBEACE",
        danger: "#B83A2F",
        "danger-deep": "#8A2D24",
        "danger-soft": "#F5DDD8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        serif: ["Source Serif 4", "serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
